server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Habilita compressão GZIP para arquivos de texto, js, css etc.
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Evita logs desnecessários para favicon e robots.txt
    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }
}
